language: php

php:
    - 7.1

jdk:
  - oraclejdk8

addons:
    apt:
        sources:
            - elasticsearch-5.x
        packages:
            - elasticsearch
            - oracle-java8-set-default

services:
    - elasticsearch

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - composer self-update
    - composer validate

install:
    - composer update --prefer-dist
    - tests/Application/bin/console doctrine:schema:create --env=test -vvv --no-interaction
    - tests/Application/bin/console ongr:es:index:create -vvv --no-interaction

script:
    - bin/phpspec run --no-interaction
    - bin/phpunit
    #- bin/behat --strict -vvv --no-interaction
