shop_api_product_show_catalog:
    path: /shop-api/taxons/{taxon_slug}/products
    methods: [GET]
    defaults:
        _controller: sylius_elastic_search.controller.search
        _format: json

shop_api_product_show_catalog_all:
    path: /shop-api/products
    methods: [GET]
    defaults:
        _controller: sylius_elastic_search.controller.search
        _format: json
