shop_api_product_show_catalog_by_code:
    path: /shop-api/taxon-products/{taxon}
    methods: [GET]
    defaults:
        _controller: sylius_elastic_search.controller.search
        _format: json

shop_api_product_show_catalog_all:
    path: /shop-api/products
    methods: [GET]
    defaults:
        _controller: sylius_elastic_search.controller.search
        _format: json
