lakion_elastic_search_shop_product_index:
    path: /products
    methods: [GET]
    defaults:
        _controller: lakion_sylius_elastic_search.controller.search:filterAction
        _sylius:
            template: "@LakionSyliusElasticSearch/Product/index.html.twig"
            resource_class: Sylius\Component\Core\Model\Product
            filter_set: products_option
    requirements:
        slug: .+
