ongr_filter_manager:
    managers:
        search_list:
            filters:
                - channel
                - taxon_code
                - price_range
                - locale
                - attribute_values
                - paginator
                - search
            repository: es.manager.default.product
    filters:
        channel:
            type: choice
            request_field: channel
            document_field: channel_code
        taxon_code:
            type: choice
            request_field: taxon_code
            document_field: taxons.code
        price_range:
            type: range
            request_field: price
            document_field: price.amount
        locale:
            type: choice
            request_field: locale_code
            document_field: locale_code
        attribute_values:
            type: multi_choice
            request_field: attribute_values
            document_field: attribute_values.value
        paginator:
            type: pager
            document_field: ~
            request_field: page
            options:
                count_per_page: 10
        search:
            type: match
            request_field: search
            document_field: name,description,attribute_values.value
            options:
                operator: and
