ongr_filter_manager:
    managers:
        search_list:
            filters:
                - channel
                - taxon_code
                - price_range
                - locale
                - paginator
                - search
                - attributes
            repository: es.manager.default.product
    filters:
        channel:
            type: choice
            request_field: channel
            document_field: channel_code
        taxon_code:
            type: choice
            request_field: taxonCode
            document_field: taxons.code
        price_range:
            type: range
            request_field: price
            document_field: price.amount
        locale:
            type: choice
            request_field: locale
            document_field: locale_code
        paginator:
            type: pager
            document_field: ~
            request_field: page
            options:
                count_per_page: 10
        attributes:
            type: multi_dynamic_aggregate
            request_field: attributes
            document_field: attributes>attributes.value
            options:
                name_field: attributes.name
        search:
            type: match
            request_field: search
            document_field: name,description,attribute_values.value
            options:
                operator: and
