ongr_filter_manager:
    managers:
        search_list:
            filters:
                - channel
                - enabled
                - taxonCode
                - taxonSlug
                - priceRange
                - locale
                - paginator
                - search
                - attributes
                - attributesByCode
                - sort
            repository: es.manager.default.product
    filters:
        channel:
            type: choice
            request_field: channel
            document_field: channel_code
        enabled:
            type: choice
            request_field: enabled
            document_field: enabled
        taxonCode:
            type: choice
            request_field: taxonCode
            document_field: taxons.code
        taxonSlug:
            type: choice
            request_field: taxonSlug
            document_field: taxons.slug
        priceRange:
            type: range
            request_field: price
            document_field: price.amount
            options:
                inclusive: true
        locale:
            type: choice
            request_field: locale
            document_field: locale_code
        paginator:
            type: sylius_elastic_search.custom_pager
            document_field: ~
            request_field: page
            options:
                limit: 10
                max_pages: 20
        attributes:
            type: multi_dynamic_aggregate
            request_field: attributes
            document_field: attributes>attributes.value
            options:
                name_field: attributes.name
        attributesByCode:
            type: sylius_elastic_search.multi_dynamic_aggregate
            request_field: attributesByCode
            document_field: attributes>attributes.value
            options:
                name_field: attributes.code
        search:
            type: match
            request_field: search
            document_field: name,description,attributes>attributes.value
            options:
                operator: and
        sort:
            type: sylius_elastic_search.sort
            request_field: sort
            document_field: ~
            options:
                aliases:
                    name: name
                    slug: slug
                    code: code
                    price: price.amount
